modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/polgaria/ExtraDiscs/issues"
[[mods]]
modId="extradiscs"
version="${file.jarVersion}"
displayName="ExtraDiscs"
displayURL="https://polgarian.life"
logoFile="icon.png"
authors="geni, davvid"
description='''
Adds in extra music discs
'''
[[dependencies.extradiscs]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extradiscs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"